FROM redis:7.2-bookworm

# Establece el directorio de trabajo
WORKDIR ./

# Copia el archivo de requisitos e instala las dependencias
COPY ./requirements.txt .
#RUN pip install --no-cache-dir -r requirements.txt
